dual_execution:
  outputs:
    ducklake:
      ## to use create your own database in MotherDuck first
      ## CREATE DATABASE jdw_ducklake 
      ##    (TYPE ducklake, DATA_PATH 's3://...')
      type: duckdb
      path: 'md:jdw_ducklake'
      threads: 1

    dev:
      type: duckdb
      path: 'md:jdw_dev'
      threads: 1

  target: ducklake