# put your configuration values here

[runtime]
log_level = "INFO"  # Options: "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
# use the dlthub_telemetry setting to enable/disable anonymous usage data reporting, see https://dlthub.com/docs/reference/telemetry
dlthub_telemetry = true

[sources.sql_database]
schema = "my_pg"
tables = [
    "call_center",
    "catalog_page",
    "catalog_returns",
    "catalog_sales",
    "customer_address",
    "customer_demographics",
    "customer",
    "date_dim",
    "household_demographics",
    "income_band",
    "inventory",
    "item",
    "promotion",
    "reason",
    "ship_mode",
    "store_returns",
    "store_sales",
    "store",
    "time_dim",
    "warehouse",
    "web_page",
    "web_returns",
    "web_sales",
    "web_site"
]
workers = 4         # Number of parallel workers for PostgreSQL extraction

[postgres]
pool_size = 4  # Match the number of workers

[data_writer]
format = "parquet"  # Use Parquet for interim storage

[destination.motherduck]
batch_size = 1000000  # Number of rows per batch for MotherDuck loading
